// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pet.Entities.Context;

#nullable disable

namespace Pet.Entities.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20220617183638_GenusAdded")]
    partial class GenusAdded
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FavoriteUser", b =>
                {
                    b.Property<int>("FavoritesId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoritesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("FavoriteUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FullAdsress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AdvertNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdvertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LivingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PetState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("LivingId");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CityNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("AdvertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6739),
                            GenusName = "Amerikan Shorthair",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6748)
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6749),
                            GenusName = "American Curl",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6749)
                        },
                        new
                        {
                            Id = 3,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6750),
                            GenusName = "Balinese",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6751)
                        },
                        new
                        {
                            Id = 4,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6752),
                            GenusName = "California Spangled",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6752)
                        },
                        new
                        {
                            Id = 5,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6753),
                            GenusName = "Chartreux",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6754)
                        },
                        new
                        {
                            Id = 6,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6754),
                            GenusName = "Ragdoll Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6755)
                        },
                        new
                        {
                            Id = 7,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6755),
                            GenusName = "Mavi Rus kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6756)
                        },
                        new
                        {
                            Id = 8,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6757),
                            GenusName = "Maine Coon",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6757)
                        },
                        new
                        {
                            Id = 9,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6758),
                            GenusName = "İran kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6758)
                        },
                        new
                        {
                            Id = 10,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6759),
                            GenusName = "British Shorthair",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6759)
                        },
                        new
                        {
                            Id = 11,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6760),
                            GenusName = "California Spangled",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6760)
                        },
                        new
                        {
                            Id = 12,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6761),
                            GenusName = "Munchkin",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6762)
                        },
                        new
                        {
                            Id = 13,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6762),
                            GenusName = "Scottish Fold",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6763)
                        },
                        new
                        {
                            Id = 14,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6763),
                            GenusName = "Norveç Orman Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6764)
                        },
                        new
                        {
                            Id = 15,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6765),
                            GenusName = "Sibirya Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6765)
                        },
                        new
                        {
                            Id = 16,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6766),
                            GenusName = "Savannah",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6766)
                        },
                        new
                        {
                            Id = 17,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6767),
                            GenusName = "Amerikan Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6767)
                        },
                        new
                        {
                            Id = 18,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6768),
                            GenusName = "Exotic Shorthair",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6768)
                        },
                        new
                        {
                            Id = 19,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6769),
                            GenusName = "Ankara kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6770)
                        },
                        new
                        {
                            Id = 20,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6771),
                            GenusName = "Himalayan Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6772)
                        },
                        new
                        {
                            Id = 21,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6773),
                            GenusName = "Kısa Tüylü Kedi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6773)
                        },
                        new
                        {
                            Id = 22,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6774),
                            GenusName = "Birman Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6774)
                        },
                        new
                        {
                            Id = 23,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6775),
                            GenusName = "Habeş Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6775)
                        },
                        new
                        {
                            Id = 24,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6776),
                            GenusName = "Bombay Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6776)
                        },
                        new
                        {
                            Id = 25,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6777),
                            GenusName = "Kinkalow",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6778)
                        },
                        new
                        {
                            Id = 26,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6778),
                            GenusName = "Oriental Shorthair",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6779)
                        },
                        new
                        {
                            Id = 27,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6779),
                            GenusName = "Ragamuffin",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6780)
                        },
                        new
                        {
                            Id = 28,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6782),
                            GenusName = "Somali Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6782)
                        },
                        new
                        {
                            Id = 29,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6783),
                            GenusName = "Singapura",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6783)
                        },
                        new
                        {
                            Id = 30,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6784),
                            GenusName = "British Longhair",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6785)
                        },
                        new
                        {
                            Id = 31,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6785),
                            GenusName = "Toyger",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6786)
                        },
                        new
                        {
                            Id = 32,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6786),
                            GenusName = "Van Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6787)
                        },
                        new
                        {
                            Id = 33,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6788),
                            GenusName = "manks kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6788)
                        },
                        new
                        {
                            Id = 34,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6789),
                            GenusName = "Donskoy Kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6789)
                        },
                        new
                        {
                            Id = 35,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6790),
                            GenusName = "Havana kedisi",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6791)
                        },
                        new
                        {
                            Id = 36,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6792),
                            GenusName = "Ocicat",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6792)
                        },
                        new
                        {
                            Id = 37,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6793),
                            GenusName = "Balinese",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6793)
                        },
                        new
                        {
                            Id = 38,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6794),
                            GenusName = "Laperm",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6794)
                        },
                        new
                        {
                            Id = 39,
                            CreateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6795),
                            GenusName = "Selkirk Rex",
                            UpdateTime = new DateTime(2022, 6, 17, 21, 36, 38, 414, DateTimeKind.Local).AddTicks(6796)
                        });
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AdvertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LivingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("LivingId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Kind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Familya")
                        .HasColumnType("int");

                    b.Property<int>("KindFamilya")
                        .HasColumnType("int");

                    b.Property<int>("KindTeam")
                        .HasColumnType("int");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kinds");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenusId")
                        .HasColumnType("int");

                    b.Property<int>("KindId")
                        .HasColumnType("int");

                    b.Property<byte>("LivingAge")
                        .HasColumnType("tinyint");

                    b.Property<bool>("LivingGender")
                        .HasColumnType("bit");

                    b.Property<string>("LivingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RacialId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("KindId");

                    b.HasIndex("RacialId");

                    b.HasIndex("UserId");

                    b.ToTable("Livings");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Racial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RacialName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Racials");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Age")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pet.Entities.Concrete.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            Id = "2864b71d-2b4d-49f2-ad7c-a6c1cdc0630d",
                            ConcurrencyStamp = "877ab6cb-3149-4208-aaed-7db31ec4617b",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "3e243413-755b-40c1-a52d-f85976a39f97",
                            ConcurrencyStamp = "4f1d0453-5614-4f5e-93f7-b76f1a8ab905",
                            Name = "BasicUser"
                        },
                        new
                        {
                            Id = "ff246bcf-b98e-496d-99e1-f8c9f0187a9b",
                            ConcurrencyStamp = "30b923bf-d357-4dbe-a2e4-3c4a271cbc7d",
                            Name = "MidUser"
                        },
                        new
                        {
                            Id = "086c741b-835c-46ce-8346-ea86cf9966b8",
                            ConcurrencyStamp = "b38a7e42-e4af-4868-a2c3-ec477edccd48",
                            Name = "HighUser"
                        },
                        new
                        {
                            Id = "0628f3a1-90e5-4e60-8eae-f80e431ec9b8",
                            ConcurrencyStamp = "74a301bc-a112-4698-8677-7ad206655b38",
                            Name = "Creator"
                        },
                        new
                        {
                            Id = "96420ad8-5075-4b4d-b100-20b47773a356",
                            ConcurrencyStamp = "24f2c7ff-ade2-4212-8376-94c9ff26f440",
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("FavoriteUser", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Favorite", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Address", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Living", "Living")
                        .WithMany()
                        .HasForeignKey("LivingId");

                    b.HasOne("Pet.Entities.Concrete.User", "User")
                        .WithMany("Advert")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Living");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.District", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Favorite", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Advert", "Advert")
                        .WithMany("Favorites")
                        .HasForeignKey("AdvertId");

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Image", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Advert", "Advert")
                        .WithMany("Image")
                        .HasForeignKey("AdvertId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Living", "Living")
                        .WithMany("Images")
                        .HasForeignKey("LivingId");

                    b.Navigation("Advert");

                    b.Navigation("Living");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Genus", "Genus")
                        .WithMany()
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Kind", "Kind")
                        .WithMany("Livings")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Racial", "Racial")
                        .WithMany()
                        .HasForeignKey("RacialId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany("Livings")
                        .HasForeignKey("UserId");

                    b.Navigation("Genus");

                    b.Navigation("Kind");

                    b.Navigation("Racial");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Address", "Addresss")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Addresss");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Kind", b =>
                {
                    b.Navigation("Livings");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.Navigation("Advert");

                    b.Navigation("Livings");
                });
#pragma warning restore 612, 618
        }
    }
}
