// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Pet.Entities.Context;

#nullable disable

namespace Pet.Entities.Migrations
{
    [DbContext(typeof(SqlDbContext))]
    [Migration("20220624191730_Imageaddedtouser")]
    partial class Imageaddedtouser
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("FavoriteUser", b =>
                {
                    b.Property<int>("FavoritesId")
                        .HasColumnType("int");

                    b.Property<string>("UsersId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("FavoritesId", "UsersId");

                    b.HasIndex("UsersId");

                    b.ToTable("FavoriteUser");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasDiscriminator<string>("Discriminator").HasValue("IdentityRole");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("DistrictId")
                        .HasColumnType("int");

                    b.Property<string>("FullAdsress")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.HasIndex("DistrictId");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<string>("AdvertNo")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("AdvertType")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("LivingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("PetState")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("LivingId");

                    b.HasIndex("UserId");

                    b.ToTable("Adverts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.City", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CityName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("CityNumber")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Cities");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.District", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CityId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DistrictName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CityId");

                    b.ToTable("Districts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<Guid?>("AdvertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Discription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Genus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("GenusName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("GenusType")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Genus");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7000),
                            GenusName = "Amerikan Shorthair",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7011)
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7013),
                            GenusName = "American Curl",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7014)
                        },
                        new
                        {
                            Id = 3,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7015),
                            GenusName = "Balinese",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7016)
                        },
                        new
                        {
                            Id = 4,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7017),
                            GenusName = "California Spangled",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7017)
                        },
                        new
                        {
                            Id = 5,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7018),
                            GenusName = "Chartreux",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7019)
                        },
                        new
                        {
                            Id = 6,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7019),
                            GenusName = "Ragdoll Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7020)
                        },
                        new
                        {
                            Id = 7,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7021),
                            GenusName = "Mavi Rus kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7021)
                        },
                        new
                        {
                            Id = 8,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7022),
                            GenusName = "Maine Coon",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7022)
                        },
                        new
                        {
                            Id = 9,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7023),
                            GenusName = "İran kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7023)
                        },
                        new
                        {
                            Id = 10,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7024),
                            GenusName = "British Shorthair",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7025)
                        },
                        new
                        {
                            Id = 11,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7025),
                            GenusName = "California Spangled",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7026)
                        },
                        new
                        {
                            Id = 12,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7027),
                            GenusName = "Munchkin",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7027)
                        },
                        new
                        {
                            Id = 13,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7028),
                            GenusName = "Scottish Fold",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7028)
                        },
                        new
                        {
                            Id = 14,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7029),
                            GenusName = "Norveç Orman Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7030)
                        },
                        new
                        {
                            Id = 15,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7030),
                            GenusName = "Sibirya Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7031)
                        },
                        new
                        {
                            Id = 16,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7032),
                            GenusName = "Savannah",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7032)
                        },
                        new
                        {
                            Id = 17,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7033),
                            GenusName = "Amerikan Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7033)
                        },
                        new
                        {
                            Id = 18,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7034),
                            GenusName = "Exotic Shorthair",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7034)
                        },
                        new
                        {
                            Id = 19,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7035),
                            GenusName = "Ankara kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7036)
                        },
                        new
                        {
                            Id = 20,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7036),
                            GenusName = "Himalayan Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7037)
                        },
                        new
                        {
                            Id = 21,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7038),
                            GenusName = "Kısa Tüylü Kedi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7038)
                        },
                        new
                        {
                            Id = 22,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7039),
                            GenusName = "Birman Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7039)
                        },
                        new
                        {
                            Id = 23,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7040),
                            GenusName = "Habeş Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7040)
                        },
                        new
                        {
                            Id = 24,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7041),
                            GenusName = "Bombay Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7042)
                        },
                        new
                        {
                            Id = 25,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7042),
                            GenusName = "Kinkalow",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7043)
                        },
                        new
                        {
                            Id = 26,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7044),
                            GenusName = "Oriental Shorthair",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7044)
                        },
                        new
                        {
                            Id = 27,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7045),
                            GenusName = "Ragamuffin",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7045)
                        },
                        new
                        {
                            Id = 28,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7046),
                            GenusName = "Somali Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7046)
                        },
                        new
                        {
                            Id = 29,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7047),
                            GenusName = "Singapura",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7048)
                        },
                        new
                        {
                            Id = 30,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7048),
                            GenusName = "British Longhair",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7049)
                        },
                        new
                        {
                            Id = 31,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7050),
                            GenusName = "Toyger",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7050)
                        },
                        new
                        {
                            Id = 32,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7051),
                            GenusName = "Van Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7051)
                        },
                        new
                        {
                            Id = 33,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7052),
                            GenusName = "manks kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7052)
                        },
                        new
                        {
                            Id = 34,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7053),
                            GenusName = "Donskoy Kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7054)
                        },
                        new
                        {
                            Id = 35,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7054),
                            GenusName = "Havana kedisi",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7055)
                        },
                        new
                        {
                            Id = 36,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7056),
                            GenusName = "Ocicat",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7056)
                        },
                        new
                        {
                            Id = 37,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7057),
                            GenusName = "Balinese",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7057)
                        },
                        new
                        {
                            Id = 38,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7058),
                            GenusName = "Laperm",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7059)
                        },
                        new
                        {
                            Id = 39,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7059),
                            GenusName = "Selkirk Rex",
                            GenusType = true,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7060)
                        },
                        new
                        {
                            Id = 40,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7061),
                            GenusName = "Buldog",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7061)
                        },
                        new
                        {
                            Id = 41,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7062),
                            GenusName = "Labrador retriever",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7062)
                        },
                        new
                        {
                            Id = 42,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7063),
                            GenusName = "Alman çoban köpeği",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7063)
                        },
                        new
                        {
                            Id = 43,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7064),
                            GenusName = "Kaniş",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7065)
                        },
                        new
                        {
                            Id = 44,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7065),
                            GenusName = "Golden Retriever",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7066)
                        },
                        new
                        {
                            Id = 45,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7067),
                            GenusName = "Chihuahua",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7067)
                        },
                        new
                        {
                            Id = 46,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7068),
                            GenusName = "Fransız buldoğu",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7068)
                        },
                        new
                        {
                            Id = 47,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7069),
                            GenusName = "Bişon çuha köpeği",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7070)
                        },
                        new
                        {
                            Id = 48,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7071),
                            GenusName = "Boksör",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7071)
                        },
                        new
                        {
                            Id = 49,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7072),
                            GenusName = "Border collie",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7072)
                        },
                        new
                        {
                            Id = 50,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7073),
                            GenusName = "Sibirya kurdu",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7073)
                        },
                        new
                        {
                            Id = 51,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7074),
                            GenusName = "Pug",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7075)
                        },
                        new
                        {
                            Id = 52,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7075),
                            GenusName = "Amerikan Staffordshire teriyeri",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7076)
                        },
                        new
                        {
                            Id = 53,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7077),
                            GenusName = "Boston Terrier",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7077)
                        },
                        new
                        {
                            Id = 54,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7078),
                            GenusName = "Cavalier King Charles Spaniel",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7078)
                        },
                        new
                        {
                            Id = 55,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7079),
                            GenusName = "Pomeranian",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7080)
                        },
                        new
                        {
                            Id = 56,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7080),
                            GenusName = "Yorkshire teriyeri",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7081)
                        },
                        new
                        {
                            Id = 57,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7081),
                            GenusName = "Bull teriyer",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7082)
                        },
                        new
                        {
                            Id = 58,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7083),
                            GenusName = "İngiliz Cocker Spaniel",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7083)
                        },
                        new
                        {
                            Id = 59,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7084),
                            GenusName = "Amerikan Eskimo Köpeği",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7085)
                        },
                        new
                        {
                            Id = 60,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7085),
                            GenusName = "Danua",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7086)
                        },
                        new
                        {
                            Id = 61,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7086),
                            GenusName = "Malta köpeği",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7087)
                        },
                        new
                        {
                            Id = 62,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7088),
                            GenusName = "Çov-çov",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7088)
                        },
                        new
                        {
                            Id = 63,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7089),
                            GenusName = "Affenpinscher",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7090)
                        },
                        new
                        {
                            Id = 64,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7090),
                            GenusName = "Basenji",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7091)
                        },
                        new
                        {
                            Id = 65,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7091),
                            GenusName = "Dakhund",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7092)
                        },
                        new
                        {
                            Id = 66,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7093),
                            GenusName = "Bretonya epanyölü",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7093)
                        },
                        new
                        {
                            Id = 67,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7094),
                            GenusName = "Bulmastif",
                            GenusType = false,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7094)
                        });
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Image", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("AdvertId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("ImageDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImagePath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid?>("LivingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AdvertId");

                    b.HasIndex("LivingId");

                    b.ToTable("Images");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Kind", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Familya")
                        .HasColumnType("int");

                    b.Property<string>("KindName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Team")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Kinds");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7324),
                            Familya = 0,
                            KindName = "Kedi",
                            Team = 0,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7325)
                        },
                        new
                        {
                            Id = 2,
                            CreateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7326),
                            Familya = 1,
                            KindName = "Köpek",
                            Team = 2,
                            UpdateTime = new DateTime(2022, 6, 24, 22, 17, 29, 923, DateTimeKind.Local).AddTicks(7327)
                        });
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("GenusId")
                        .HasColumnType("int");

                    b.Property<int>("KindId")
                        .HasColumnType("int");

                    b.Property<byte>("LivingAge")
                        .HasColumnType("tinyint");

                    b.Property<bool>("LivingGender")
                        .HasColumnType("bit");

                    b.Property<string>("LivingName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("GenusId");

                    b.HasIndex("KindId");

                    b.HasIndex("UserId");

                    b.ToTable("Livings");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<int>("AddressId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Age")
                        .HasColumnType("datetime2");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<bool>("Gender")
                        .HasColumnType("bit");

                    b.Property<Guid?>("ImageId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTime>("UpdateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("ImageId");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Pet.Entities.Concrete.UserRole", b =>
                {
                    b.HasBaseType("Microsoft.AspNetCore.Identity.IdentityRole");

                    b.HasDiscriminator().HasValue("UserRole");

                    b.HasData(
                        new
                        {
                            Id = "e7943686-3e24-44af-9be1-33123f91453d",
                            ConcurrencyStamp = "6378cefc-97fa-4e0f-b5d1-20dd483cc260",
                            Name = "Admin"
                        },
                        new
                        {
                            Id = "cb3d57a3-5563-40bb-9301-d685f72e4836",
                            ConcurrencyStamp = "f1e788e1-196a-4f29-938b-57fc3f89fbab",
                            Name = "BasicUser"
                        },
                        new
                        {
                            Id = "76bd3236-8251-45c0-b1c6-48ac311a65d1",
                            ConcurrencyStamp = "2bfef952-eab6-4258-93a8-5aeb48d42a46",
                            Name = "MidUser"
                        },
                        new
                        {
                            Id = "b78e9b01-72fe-4fbf-abc9-45e18ad2c5dc",
                            ConcurrencyStamp = "ec2e5c8a-68e1-432e-b5e3-8b6b1acf0fa1",
                            Name = "HighUser"
                        },
                        new
                        {
                            Id = "626333d8-e129-4854-abca-536cd86899ea",
                            ConcurrencyStamp = "f05d6be3-2e5d-4a73-9d09-6289dcc46b46",
                            Name = "Creator"
                        },
                        new
                        {
                            Id = "e48703d2-876c-4db1-9b07-f73ae5fed3bb",
                            ConcurrencyStamp = "60052a00-f961-4990-94f1-9d89e3d5f6c6",
                            Name = "Editor"
                        });
                });

            modelBuilder.Entity("FavoriteUser", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Favorite", null)
                        .WithMany()
                        .HasForeignKey("FavoritesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UsersId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Address", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.City", "City")
                        .WithMany()
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.District", "District")
                        .WithMany()
                        .HasForeignKey("DistrictId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");

                    b.Navigation("District");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Living", "Living")
                        .WithMany()
                        .HasForeignKey("LivingId");

                    b.HasOne("Pet.Entities.Concrete.User", "User")
                        .WithMany("Advert")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("Living");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.District", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.City", "City")
                        .WithMany("Districts")
                        .HasForeignKey("CityId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("City");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Favorite", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Advert", "Advert")
                        .WithMany("Favorites")
                        .HasForeignKey("AdvertId");

                    b.Navigation("Advert");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Image", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Advert", "Advert")
                        .WithMany("Image")
                        .HasForeignKey("AdvertId");

                    b.HasOne("Pet.Entities.Concrete.Living", "Living")
                        .WithMany("Images")
                        .HasForeignKey("LivingId");

                    b.Navigation("Advert");

                    b.Navigation("Living");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Genus", "Genus")
                        .WithMany()
                        .HasForeignKey("GenusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Kind", "Kind")
                        .WithMany("Livings")
                        .HasForeignKey("KindId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.User", "User")
                        .WithMany("Livings")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Genus");

                    b.Navigation("Kind");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.HasOne("Pet.Entities.Concrete.Address", "Addresss")
                        .WithMany()
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Pet.Entities.Concrete.Image", "Image")
                        .WithMany()
                        .HasForeignKey("ImageId");

                    b.Navigation("Addresss");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Advert", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Image");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.City", b =>
                {
                    b.Navigation("Districts");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Kind", b =>
                {
                    b.Navigation("Livings");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.Living", b =>
                {
                    b.Navigation("Images");
                });

            modelBuilder.Entity("Pet.Entities.Concrete.User", b =>
                {
                    b.Navigation("Advert");

                    b.Navigation("Livings");
                });
#pragma warning restore 612, 618
        }
    }
}
